"""Add MarketAnalysis model

Revision ID: 034ef6430dfb
Revises: a3830a4212f4
Create Date: 2025-09-13 15:13:22.181773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '034ef6430dfb'
down_revision: Union[str, Sequence[str], None] = 'a3830a4212f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('progress_updates', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_analyses_id'), 'market_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_analyses_id'), table_name='market_analyses')
    op.drop_table('market_analyses')
    # ### end Alembic commands ###
