"""Change embedding dimension

Revision ID: a3830a4212f4
Revises: 0b0db5515ae9
Create Date: 2025-09-11 16:48:33.332006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'a3830a4212f4'
down_revision: Union[str, Sequence[str], None] = '0b0db5515ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facts', 'embedding',
               existing_type=Vector(1536),
               type_=Vector(384),
               existing_nullable=True)
    op.alter_column('pages', 'embedding',
               existing_type=Vector(1536),
               type_=Vector(384),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'embedding',
               existing_type=Vector(384),
               type_=Vector(1536),
               existing_nullable=True)
    op.alter_column('facts', 'embedding',
               existing_type=Vector(384),
               type_=Vector(1536),
               existing_nullable=True)
    # ### end Alembic commands ###
